-- Reversão da migração 20260913170000_pericia_padrao_da_casa_nos_em_analise
-- Gerada em 2026-09-13T16:39:25.163Z a partir de leitura da produção, ANTES de aplicar.
-- Devolve pericia e laudo_pericia exatamente ao que eram. Aplicar pelo pooler
-- (node supabase/manutencao/aplicar-migracao.js <este arquivo>) — a chave de
-- serviço é recusada em silêncio pela trava de estoque_motors.
begin;
update public.estoque_motors set pericia = $rev$Em análise$rev$, laudo_pericia = $rev$Laudo cautelar completo — estrutura, chassi e histórico de sinistro auditados por empresa credenciada junto ao Detran$rev$ where id = 7416830;  -- ford ka se plus 1.0 ha c
update public.estoque_motors set pericia = $rev$Em análise$rev$, laudo_pericia = $rev$Laudo cautelar completo — estrutura, chassi e histórico de sinistro auditados por empresa credenciada junto ao Detran$rev$ where id = 7447739;  -- harley-davidson dyna glide super glide fxd
update public.estoque_motors set pericia = $rev$Em análise$rev$, laudo_pericia = $rev$Laudo cautelar completo — estrutura, chassi e histórico de sinistro auditados por empresa credenciada junto ao Detran$rev$ where id = 7812719;  -- fiat argo drive 1.0
update public.estoque_motors set pericia = $rev$Em análise$rev$, laudo_pericia = $rev$Laudo cautelar completo — estrutura, chassi e histórico de sinistro auditados por empresa credenciada junto ao Detran$rev$ where id = 7947766;  -- bmw x4 m40i 3.0 m sport edit v6 turbo aut
update public.estoque_motors set pericia = $rev$Em análise$rev$, laudo_pericia = $rev$Laudo cautelar completo — estrutura, chassi e histórico de sinistro auditados por empresa credenciada junto ao Detran$rev$ where id = 8137195;  -- kia bongo k-2500 2.5 4x2
update public.estoque_motors set pericia = $rev$Em análise$rev$, laudo_pericia = $rev$Laudo cautelar completo — estrutura, chassi e histórico de sinistro auditados por empresa credenciada junto ao Detran$rev$ where id = 8152210;  -- volkswagen parati cl 1.6 mi 4p
update public.estoque_motors set pericia = $rev$Em análise$rev$, laudo_pericia = $rev$Laudo cautelar completo — estrutura, chassi e histórico de sinistro auditados por empresa credenciada junto ao Detran$rev$ where id = 8191855;  -- hyundai hb20 comfort 1.0 flex 12v mec.
update public.estoque_motors set pericia = $rev$Em análise$rev$, laudo_pericia = $rev$Laudo cautelar completo — estrutura, chassi e histórico de sinistro auditados por empresa credenciada junto ao Detran$rev$ where id = 8193514;  -- ford ecosport 2.0 titanium 16v flex 4p automatico
update public.estoque_motors set pericia = $rev$Em análise$rev$, laudo_pericia = $rev$Laudo cautelar completo — estrutura, chassi e histórico de sinistro auditados por empresa credenciada junto ao Detran$rev$ where id = 8256747;  -- bmw 320i 2.0 sport gp active flex aut
update public.estoque_motors set pericia = $rev$Em análise$rev$, laudo_pericia = $rev$Laudo cautelar completo — estrutura, chassi e histórico de sinistro auditados por empresa credenciada junto ao Detran$rev$ where id = 8310901;  -- volkswagen fusca 1300l
update public.estoque_motors set pericia = $rev$Em análise$rev$, laudo_pericia = $rev$Laudo cautelar completo — estrutura, chassi e histórico de sinistro auditados por empresa credenciada junto ao Detran$rev$ where id = 8333811;  -- volkswagen kombi standard 1.4 mi
update public.estoque_motors set pericia = $rev$Em análise$rev$, laudo_pericia = $rev$Laudo cautelar completo — estrutura, chassi e histórico de sinistro auditados por empresa credenciada junto ao Detran$rev$ where id = 8335025;  -- ford ka sedan se 1.5 12v
update public.estoque_motors set pericia = $rev$Em análise$rev$, laudo_pericia = $rev$Laudo cautelar completo — estrutura, chassi e histórico de sinistro auditados por empresa credenciada junto ao Detran$rev$ where id = 8335204;  -- volkswagen saveiro 1.6 msi robust cs 8v flex 2p manual
update public.estoque_motors set pericia = $rev$Em análise$rev$, laudo_pericia = $rev$100% aprovada em mais de 120 itens de inspeção.$rev$ where id = 8358193;  -- volkswagen saveiro trendline 1.6 total flex 16v
update public.estoque_motors set pericia = $rev$Em análise$rev$, laudo_pericia = $rev$Laudo cautelar completo — estrutura, chassi e histórico de sinistro auditados por empresa credenciada junto ao Detran$rev$ where id = 8392516;  -- volkswagen kombi standard 1.4mi 4p
update public.estoque_motors set pericia = $rev$Em análise$rev$, laudo_pericia = $rev$Laudo cautelar completo — estrutura, chassi e histórico de sinistro auditados por empresa credenciada junto ao Detran$rev$ where id = 8393824;  -- volkswagen voyage 1.6 trend
update public.estoque_motors set pericia = $rev$Em análise$rev$, laudo_pericia = $rev$Laudo cautelar completo — estrutura, chassi e histórico de sinistro auditados por empresa credenciada junto ao Detran$rev$ where id = 8402155;  -- volkswagen virtus highline 200 tsi 1.0 flex 12v aut.
update public.estoque_motors set pericia = $rev$Em análise$rev$, laudo_pericia = $rev$Laudo cautelar completo — estrutura, chassi e histórico de sinistro auditados por empresa credenciada junto ao Detran$rev$ where id = 8407873;  -- volkswagen polo track 1.0 flex 12v 5p
update public.estoque_motors set pericia = $rev$Em análise$rev$, laudo_pericia = $rev$Laudo cautelar completo — estrutura, chassi e histórico de sinistro auditados por empresa credenciada junto ao Detran$rev$ where id = 8416946;  -- chevrolet celta 1.0l lt
update public.estoque_motors set pericia = $rev$Em análise$rev$, laudo_pericia = null where id = 8446229;  -- chevrolet spin advantage 1.8 8v econo.flex 5p aut.
commit;
